#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py makemigrations
python manage.py migrate
python manage.py collectstatic --noinput 

{%- if cookiecutter.use_async == 'y' %}
uvicorn config.asgi:application --host 0.0.0.0 --reload
{%- else %}
python manage.py runserver_plus 0.0.0.0:8000
{%- endif %}
